### ISSUE TITLE
Minor Issue: Login Screen

### ISSUE THREAD

**Issue by iStormUK** [crummysummy/Issues-Visco-Therapy-Legacy#21]
Minor issue, does not impact functionality.

When you start the browser, occasionally it remembers the last page you were on, and having timed out your connection asks you to input your password and username.

This login screen is not formatted at all, just white, two boxes and a submit button; screenshot attached with example link used in address bar for refernce
![capture](https://user-images.githubusercontent.com/16283629/29162007-11a922b6-7db0-11e7-9703-568fbdf60cc0.PNG)

**Comment by crummysummy** [comment]
Thanks for reporting. Will get this fix ready for the move.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by crummysummy** [comment]
Issue has bee resolved. The fix is not yet on the Staging website however will be eventually in a future deployment. It will be there for the AWS Go Live however. #15
