### ISSUE TITLE
Enhancement: Issues list Screen

### ISSUE THREAD

**Issue by iStormUK** [crummysummy/Issues-Visco-Therapy-Legacy#22]
Issues List screen often lists collections as well as outstanding issues.  With the issues we can click them to open.  No such interaction possible with the collections, yet these are often as important to check on.

More of a minor lifestyle improvement, but would be tres handy

**Comment by crummysummy** [comment]
Hi @iStormUK - Just to make sure, are you referring to this section?

<img width="885" alt="screen shot 2017-08-17 at 17 43 56" src="https://user-images.githubusercontent.com/5438978/29423464-bde56cc4-8373-11e7-8895-46010cbeadf3.png">

If this is the section you are referring to, would you just like me to:
- Make Collection ID clickable
- Make Issue Tracking ID clickable

Side note :- Myself & @LeeVT would like to overhaul ITS completely (rather then adding/fixing the currently dated application) however that would be a longterm project that requires a lot of planning. Any suggestions would be best to forward to @LeeVT . Any ideas of making you and your co-workers lives easier should be a good one!

Cheers

**Comment by iStormUK** [comment]
Well, can this idea for the moment; I’ll liaise with Courtney and Khalisa, see what ideas they want, run some by them. Mock up a concept that may work and pop that up in an issue, or likely more than one if deemed to require it.  That sound good?  Can probably doodle up a concept.

As an interim though, be nice if issue numbers, where displayed on the site, were consistent and clickable, in this way at least everyone knows ‘if I see #00000 I can click to see the issue’ wherever they see it.

Sent from Mail for Windows 10

**Comment by LeeVT** [comment]
@iStormUK I have created suggestions board on trello, any ideas that you have for the issue tracker or anything in general pop in there

**Comment by crummysummy** [comment]
@iStormUK @LeeVT for the time being, I will make the Collection & Issue IDs as links on the ITS Dashboard from the screenshot i posted earlier.

@LeeVT As discussed, we plan on overhauling ITS in the future but this should be quick thing for me to add in.

## Task For Dev

- [ ] Make Collection & Issue IDs as links on ITS dashboard

**Comment by crummysummy** [comment]
Feature has been implemented ready for the AWS move #15 .
This can been seen on the Staging website.
