### ISSUE TITLE
Sage 200 Dispatch Order Manual Upload Test

### ISSUE THREAD

**Issue by crummysummy** [crummysummy/Issues-Visco-Therapy-Legacy#23]
@LeeVT 
Please can you generate  (or request from Jasmine) a Sage 200 report for Dispatched Orders (The one that SOP Department use to manually upload into the VT website) for the date '2017-08-15'.

Please email me this report in a CSV format.

**Comment by LeeVT** [comment]
@crummysummy i have sent this to you via email

**Comment by crummysummy** [comment]
Feature works as expected.

All this feature is meant to do is upload order data to the old database tables for orders and process Amazon dispatch emails.

The data is then used within ITS & search only.

The Sage 200 Order area does not use any of this information from what I can see.
