### ISSUE TITLE
Add Email Queue Log Viewer To Admin Panel

### ISSUE THREAD

**Issue by crummysummy** [crummysummy/Issues-Visco-Therapy-Legacy#3]

**Comment by crummysummy** [comment]
@LeeVT I have pushed an update to the Staging site so we can easily see the Website's email queue.

Nothing for you to test however if you take a look if you want. You will find a link under System on the Admin Panel.

You have been given permission to view the page. For obviously reasons, you should not open access to these pages to everything given the sensitive nature of the emails as they may contain highly specific data on Non customer's and staff such as passwords (there may be old systems that send the password in plaintext which I cannot remember if I removed or now).

**Comment by LeeVT** [comment]
@crummysummy Thats really helpful. Thanks
