### ISSUE TITLE
Final Client Testing

### ISSUE THREAD

**Issue by crummysummy** [crummysummy/Issues-Visco-Therapy-Legacy#31]
@LeeVT Getting close to moving.

Can we get Jasmine to spot check a few areas of the site to ensure her side of things such as Courier Upload CSV file & anything else in her realm of things? Her area is quite important so need to ensure it works before we start making the switch.

**Comment by LeeVT** [comment]
@crummysummy I will pass this onto her

**Comment by crummysummy** [comment]
Client signed off.
