### ISSUE TITLE
413 Request Entity Too error

### ISSUE THREAD

**Issue by LeeVT** [crummysummy/Issues-Visco-Therapy-Legacy#4]
When I upload the file to Sage to SCS file uploader i receive an error

413 Request Entity Too 

nginx #

**Comment by LeeVT** [comment]
This is also the same for dispatch order upload

**Comment by LeeVT** [comment]
Also happened when approving a warranty application

**Comment by crummysummy** [comment]
Can you email me sample upload files please?

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LeeVT** [comment]
sent via email

**Comment by crummysummy** [comment]
May have answer for the issue caused. Setting on server. Will confirm fix tomorrow morning hopefully.

The error is related to Nginx server setup '413 Request Entity Too Large'

# Task for Lee
@LeeVT I need you to email DATAEXCHANGE order export csv files. I am hoping you will find copies within the Dataexchange folder (these are the ones that are normally FTP'ed into the existing server)

**Comment by crummysummy** [comment]
@LeeVT Server has been updated to allow for large file uploads.
Please can you provide the sample Dataexchange order export CSV files via email so I can test those myself.

Please can you test the Sage SCS import and another other imports and check to make sure you see expected changes to occur on the data.

**Comment by LeeVT** [comment]
@crummysummy 


I have sent you the DATAEXCHANGE order export csv file which i hope is the correct one

I have tested sage to scs, dispatch order export and works fine

Upload to invoice (http://viscotherapy-legacy.staging.lemonmonkeys.com/admin/customers/invoices/upload/) gives

504 Gateway Time-out

nginx

**Comment by crummysummy** [comment]
@LeeVT has confirmed that uploads are now working and the 413 error no longer appears.
Dataexchange test will be carried out under issue #16 by myself.

Closing ticket.
