### ISSUE TITLE
Invoice Upload data

### ISSUE THREAD

**Issue by LeeVT** [crummysummy/Issues-Visco-Therapy-Legacy#5]
I cannot upload invoices anymore which really we need to use sage

so either need to re-add upload invoice or remove the following 

Sales Data
View Customer Invoices
View Customer Dispatched Orders

**Comment by crummysummy** [comment]
Can you email me sample upload files please?

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LeeVT** [comment]
i have emailed this to you

**Comment by crummysummy** [comment]
@LeeVT So is the upload feature still in use then? Data is not being pulled in via Dataexchange?

**Comment by crummysummy** [comment]
@LeeVT I have brought about the Upload Feature. Please can you test to ensure it works. I have not test it myself at this point however I assume that if the other uploads fail then this will probably fail too.

**Comment by LeeVT** [comment]
Upload to invoice (http://viscotherapy-legacy.staging.lemonmonkeys.com/admin/customers/invoices/upload/) gives

504 Gateway Time-out

nginx

**Comment by crummysummy** [comment]
Ok, easy enough. File to large and taking it's time. I'll implement the quick fix that's technically not ideal but same thing I did on old site! 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by crummysummy** [comment]
@LeeVT You have not emailed an invoice import file to me.

**Comment by LeeVT** [comment]
@crummysummy i have emailed this to you

**Comment by crummysummy** [comment]
File has been tested and everything works as desired. 

I have notice an invoice/credit note type issue upon upload which was easy enough to fix. This has been lined up for the next deploy. Closing.

**Comment by crummysummy** [comment]
@LeeVT 

Actually, Lee, can you perform one more use test. 

Can you import a recent/export and upload a a Sage 200 Invoice file to the Staging site please?

## Client Task
Upload a recent Sage 200 Invoice file 'Invoice Export For VT Site' to: http://viscotherapy-legacy.staging.lemonmonkeys.com/admin/upload_invoice.php

I would like a confirmation that you receive no **HTTP Timeout/Bad Gateway errors.** 

If you receive problems, please email me the file & screenshot of the error.

**Comment by LeeVT** [comment]
@crummysummy First time i got the banner to load after a while but second time it took ages to load and then got 504 Gateway Time-out

**Comment by crummysummy** [comment]
Lee has sent me the file and screenshot via email. I will test and implement a fix.

**Comment by crummysummy** [comment]
Issue is proving difficult to resolve. Core issue is the file being uploaded contains a month worth of data. The script cannot handle it on the low powered version of the server. No in-session improvements made so far can get it to work properly so i need to rewrite it completely to allow the user to upload the file and have a cron schedule process the file in small batches.

**Comment by LeeVT** [comment]
@crummysummy Usually I would upload it monthly, however, can do it every other week if needed so its smaller batches

**Comment by crummysummy** [comment]
@LeeVT Please can you test the invoice upload by uploading invoices from Last week in SEPTEMBER.

The script will upload the file instantly and then the cron scheduler will process 20 rows every 1 minute. A log is displayed on page which will update when you refresh the page. Check to make sure invoices appear within http://viscotherapy-legacy.staging.lemonmonkeys.com/admin/customer_invoices.php

Let me know what the outcome is.

**Comment by LeeVT** [comment]
@crummysummy it worked - File was uploaded successfully. It will be processed in due course via the scheduler. I uploaded one from 4/9 to 10/9

**Comment by crummysummy** [comment]
@LeeVT Please can you confirm if the data looks correct to you based on the file you have imported. Just to confirm if the values look correct and nothing is missing or in the wrong place.

**Comment by LeeVT** [comment]
@crummysummy I receive an error message when going to the link - No such file or directory

**Comment by crummysummy** [comment]
@LeeVT Database was dying. I think i sorted it. Please try again.

**Comment by LeeVT** [comment]
@crummysummy The type collum is black and for total it says please contact us. Clicking on it next tax and gross also says contact us, other than that its fine

**Comment by LeeVT** [comment]
@crummysummy Yes the data is the same as the old version so works fine

**Comment by crummysummy** [comment]
@LeeVT Perfect. Marking this as done.
