### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by LeeVT** [crummysummy/Issues-Visco-Therapy-Legacy#6]
There is a typing error on home page - VIST OUR PUBLIC WEBSITE should be VISIT OUR PUBLIC WEBSITE
![spelling](https://user-images.githubusercontent.com/30863940/29120142-ec89b130-7d00-11e7-9e20-e68678fa5b5f.png)

**Comment by crummysummy** [comment]
Development has been completed. Will be closed when AWS Go Live #20 is done.
