### ISSUE TITLE
Remove the link section in SCS + Change name

### ISSUE THREAD

**Issue by LeeVT** [crummysummy/Issues-Visco-Therapy-Legacy#8]
Remove the links (see image) and change SCS to stock control system name to just stock
![a](https://user-images.githubusercontent.com/30863940/29120248-5b7e8656-7d01-11e7-939a-7caca776bfcf.png)
![b](https://user-images.githubusercontent.com/30863940/29120250-5ecfce46-7d01-11e7-92fe-115d1b1acf4e.png)

**Comment by crummysummy** [comment]
Development has been completed on this and will appear on the Staging site later on and will come into affect via the AWS Go Love #20 

I also removed the 'Site Product Reference' from the Edit page as that is linked to the now removed feature, Products.
